version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=local_llm_chat.settings
      - DATABASE_URL=postgres://postgres:postgres@db:5432/local_llm
      - REDIS_URL=redis://redis:6379/0
      - GUNICORN_CMD_ARGS=--workers=2 --threads=2 --timeout=120 --max-requests=1000 --max-requests-jitter=50
    depends_on:
      - db
      - redis
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 1G

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=local_llm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    deploy:
      resources:
        limits:
          memory: 512M

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          memory: 256M

volumes:
  postgres_data: 